name: Node CI

on: 
  push:
    branches:
      - main

jobs:

  checkCodestyle:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: [8.x, 10.x, 12.x, 14.x, 16.x, 18.x]
    - name: Install and check codestyle
      run: |
        npm install
        npm run codestyle
      env:
        CI: true
